CREATE ROLE trip WITH LOGIN PASSWORD 'secret';
CREATE DATABASE tripdb;
GRANT ALL PRIVILEGES ON DATABASE tripdb TO trip;

CREATE ROLE holiday WITH LOGIN PASSWORD 'secret';
CREATE DATABASE holidaydb;
GRANT ALL PRIVILEGES ON DATABASE holidaydb TO holiday;
