version: "3"
services:
  postgres:
    image: "postgres:14.1"
    environment:
      POSTGRES_PASSWORD: "sapwd"
    ports:
      - "5432:5432"
    volumes:
      - ./db-init/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
